# Generated by Django 5.2.11 on 2026-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0009_wallsection_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='wallsection',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='图片'),
        ),
    ]
