# Generated by Django 5.2.11 on 2026-08-16 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0010_alter_usercontribution_image_alter_wallsection_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallsection',
            name='built_year_confidence',
            field=models.CharField(choices=[('confirmed', '我确定'), ('guess', '我推测')], default='confirmed', max_length=10, verbose_name='建造年代可信度'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='built_year_reason',
            field=models.TextField(blank=True, null=True, verbose_name='建造年代推测理由'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='challenge_count',
            field=models.IntegerField(default=0, verbose_name='质疑人数'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='discovery',
            field=models.TextField(blank=True, help_text='关于这段城墙，你有什么有趣的发现或猜想？', null=True, verbose_name='探究发现'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='dispute_status',
            field=models.CharField(choices=[('normal', '正常'), ('pending', '待考证')], default='normal', max_length=10, verbose_name='争议状态'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='evidence_count',
            field=models.IntegerField(default=0, verbose_name='补充证据人数'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='length_confidence',
            field=models.CharField(choices=[('confirmed', '我确定'), ('guess', '我推测')], default='confirmed', max_length=10, verbose_name='长度可信度'),
        ),
        migrations.AddField(
            model_name='wallsection',
            name='length_reason',
            field=models.TextField(blank=True, null=True, verbose_name='长度推测理由'),
        ),
        migrations.CreateModel(
            name='WallFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('evidence', '补充证据'), ('challenge', '不同看法')], max_length=10, verbose_name='反馈类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
                ('wall_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='wall_app.wallsection', verbose_name='城墙段落')),
            ],
            options={
                'verbose_name': '城墙反馈',
                'verbose_name_plural': '城墙反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
