# Generated by Django 5.2.11 on 2026-08-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0011_wallsection_built_year_confidence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
