# Generated by Django 5.2.11 on 2026-08-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0013_delete_usercontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='description_confidence',
            field=models.CharField(choices=[('confirmed', '我确定'), ('guess', '我推测')], default='confirmed', max_length=10, verbose_name='描述可信度'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='description_reason',
            field=models.TextField(blank=True, null=True, verbose_name='描述推测理由'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='year_confidence',
            field=models.CharField(choices=[('confirmed', '我确定'), ('guess', '我推测')], default='confirmed', max_length=10, verbose_name='年份可信度'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='year_reason',
            field=models.TextField(blank=True, null=True, verbose_name='年份推测理由'),
        ),
    ]
